config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :users, only: [:show]

  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:index, :create, :destroy]
    end
  end

  post :incoming, to: 'incoming#create'

  get  'about' => 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  has_many :likes, dependent: :destroy

  def like_present_for(user)
    likes.find_by(user: user)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many  :topics
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)

    @bookmark.user = current_user
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was saved!"
      redirect_to @topic
    else
      flash.now[:alert] = "An error occurred. Please try again."
      render :new
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)

    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated."
      redirect_to @bookmark.topic
    else
      flash[:alert] = "An error occurred. Please try again."
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted."
      redirect_to @bookmark.topic
    else
      flash[:alert] = "An error occurred. Please try again."
      render :show
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
# closes class
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!, only: [:create]

  def create
    user = User.find_by(email: params[:sender])

    if user.nil?
      head 404
    else
      topic = Topic.find_or_create_by(user: user, title: params[:subject])
      topic.bookmarks.create(url: params["body-plain"])
      head 200
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    # @topic = Topic.find(params[:topic_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like

    if like.save
      flash[:notice] = "Like was saved successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "Error creating like. Please try again."
      redirect_to @topic
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    # @topic = Topic.includes(bookmarks: :likes).find(params[:id])
    like = Like.find(params[:id])

    authorize like
    if like.destroy
      flash[:notice] = "Like was deleted successfully."
      redirect_to @bookmark
    else
      flash.now[:alert] = "There was an error deleting the like."
      redirect_to @topic
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.includes(bookmarks: :likes).find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      flash[:notice] = "Topic created successfully!"
      redirect_to @topic
    else
      flash.now[:alert] = "An error occurred. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic updated successfully!"
      redirect_to @topic
    else
      flash.now[:alert] = "An error occurred. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" Topic was deleted!"
      redirect_to action: :index
    else
      flash.now[:alert] = "An error occurred. Please try again."
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end

# closes class
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    #populate @user_bookmarks with user's bookmarks
    @user_bookmarks = Bookmark.where(:user_id => current_user.id)
    #populate @liked_bookmarks with liked bookmarks
    @liked_bookmarks = Like.where(:user_id => current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for [topic, bookmark]  do |f| %>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark URL" %>
  </div>
  <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
 </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit:<%= @bookmark.url %></h1>
<%= render partial: 'form', locals: { topic: @bookmark.topic, bookmark: @bookmark } %>

app/views/bookmarks/new.html.erb
<h1> New Bookmark</h1>
<%= render partial: 'form', locals: { topic: @topic, bookmark: @topic.bookmarks.new } %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.url %></h1>
  <% if policy(@bookmark).update?%>
    <%= link_to "Edit", edit_topic_bookmark_path, class: 'btn btn-info btn-small' %>
  <br>
  <% end %>
  <% if policy(@bookmark).destroy?%>
    <%= link_to "Delete", [@bookmark.topic, @bookmark],
  class: 'btn btn-danger btn-small',
  method: :delete, data: { confirm: 'Are you sure you want to delete this bookmark' } %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaeMarks</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "KaeMarks", topics_path %></li>

        <% if user_signed_in? %>
          <div class = 'pull-right'>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "User Profile", users_show_path, :class => 'navbar-link' %> -
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete,
            :class => 'navbar-link' %>
          </div>
        <% else %>
          <div class = 'pull-right'>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          </div>
        <% end %>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = bookmark.like_present_for(current_user) %>
      <%= link_to [@topic, bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [@topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<% @likes.each do |like| %>
  <div>
    <p>User: <%= like.user_id %></p>
    <p>Bookmark: <%= like.bookmark.id %></p>
  </div>
<% end %>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter a Topic name" %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Topic:</p>
    <ul>
      <li>Be Specific</li>
      <li>Be Brief</li>
      <li>Be Funny</li>
    </ul>
    <div class="col-md-8">
      <%= render partial: "form", locals: { topic: @topic } %>
    </div>
  </div>

app/views/topics/index.html.erb
<h1>Topics</h1>
<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to topic.title, topic %>
        </h4>
        <small>
          <% topic.bookmarks %>
        </small>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>    
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Topic:</p>
    <ul>
      <li>Be Specific</li>
      <li>Be Brief</li>
      <li>Be Funny</li>
    </ul>
    <div class="col-md-8">
      <%= render partial: "form", locals: { topic: @topic } %>
    </div>
  </div> 

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<div class="row">
  <div class="col-md-8">
    <h4>Bookmarks</h4>
    <% @topic.bookmarks.each do |bookmark| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to bookmark.url, [bookmark.topic, bookmark] %>
          </h4>
          <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-primary' %>
    <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
    <%= link_to "Delete Topic",  @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %>'s bookmarks</h1>
<div class= "row">
  <h3>Bookmarks</h3>
  <div class="col-md-8">
    <% @user_bookmarks.each do |bookmark| %>
    <h5><%= bookmark.url %></h5>
    <%= link_to "Delete", topic_bookmark_path(bookmark.topic_id, bookmark),
        method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this bookmark?'} %>
    <% end %>
  </div>
</div>
<div class="row">
  <h3>Liked Bookmarks</h3>
  <div class="col-md-8">
    <% @liked_bookmarks.each do |like| %>
    <% bookmark = Bookmark.find(like.bookmark_id) %>
    <h5><%= bookmark.url %></h5>
      <%= link_to [@user], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"></i>&nbsp; Unlike
      <% end %>
    <% end %>
    </div>
</div>

app/views/welcome/about.html.erb
<h1>About KaeMarks</h1>
  <h3>Brief</h3>
    <p>KaeMarks is a Rails application that allow users to bookmark URLs
        by email, check out others' bookmarks and organize their bookmarks.</p>

  <h3>User Stories:</h3>
    <br>
    <p>Below is a list of user stories, I was required to complete in order to
      build this application.</p>
      <ul>
        <li>As a user, I want to sign up for a free account by providing a user name, password and email.</li>
        <li>As a user, I want to sign in and out of KaeMarks.</li>
        <li>As a user, I want to email a URL to KaeMarks and have it saved
          in the KaeMarks database.</li>
        <li>As a user, I want to see an index of all topics and
          their bookmarks.</li>
        <li>As a user, I want to create, read, update, and delete bookmarks.</li>
        <li>As a user, I want to be the only one allowed to delete and
          update my bookmarks.</li>
        <li>As a user, I want to "like and unlike" bookmarks
          created by other users.</li>
        <li>As a user, I want to see a list of bookmarks on my personal
          profile that I've added or liked.</li>
      </ul>

    <p>I used several gems such as devise, letter_opener and faker to add
      Authentication, fake data and efficiency to the application.</p>
      <br>
  <p> This application was built as part of Bloc's final project curriculum.</p>
  <small>Created by Ashleigh White</small>

app/views/welcome/index.html.erb
<h1>Welcome to KaeMarks</h1>
<div class="container">
  <div class= "jumbotron">
    <ul>
      <li>Do you ever get overwhelmed looking at your list of bookmarks?</li>
      <li>Have you ever wished you could share your bookmarks with others?</li>
      <li>Do you want a fun, colorful, easy way to organize your bookmarks?</li>
    </ul>
    <br>
    <p>If you have answered yes to any of these questions, then KaeMarks is the
      solution for you!</p>
      <button class="start-btn" type="button">
        <%= link_to "Begin Here", topics_path %>
      </button>
    </div>
  </div>